# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Meson

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy cython pytest ninja
        python -m pip install git+https://github.com/mesonbuild/meson.git@master
    - name: Build
      run: |
        meson setup build --prefix=$PWD/installdir
    - name: Compile
      run: |
        meson compile -C build
    - name: Install
      run: |
        meson install -C build
    - name: Test pure python
      run: |
        export PYTHONPATH=$PWD/installdir/lib/python3.8/site-packages
        python -c "from mc_lib.tests.test_cubic_lattice import test_roundtrip; test_roundtrip"
    - name: Test pytest
      run: |
        pytest mc_lib -v --pyargs
    - name: Test example
      run: |
        cd examples
        python setup.py build_ext --inplace
        python -c'from cy_ising import simulate; simulate(4, 1.25, 20000)'

